Repository AllenNeuralDynamics/aind-data-schema, pull requests merged in 2023-05, with the labels that each got.

#301 Docs 300 improve readme
  README.md
  examples/aibs_smartspim_procedures.json
  examples/procedures.json
  src/aind_data_schema/procedures.py
Labels: documentation, help wanted

#303 Adding ROR IDs to institution
  examples/aibs_smartspim_procedures.json
  examples/data_description.json
  examples/procedures.json
  examples/subject.json
  src/aind_data_schema/base.py
  src/aind_data_schema/data_description.py
  src/aind_data_schema/procedures.py
  src/aind_data_schema/subject.py
Labels: enhancement

#317 ainds_utils class, plus function to inspect currently imported modules
  .gitignore
  examples/subject.py
  src/aind_data_schema/base.py
  src/aind_data_schema/behavior/behavior_rig.py
  src/aind_data_schema/device.py
  src/aind_data_schema/ephys/ephys_session.py
  src/aind_data_schema/ophys/ophys_rig.py
  src/aind_data_schema/stimulus.py
  src/aind_data_schema/utils/aind_utils.py
  tests/test_utils.py
Labels: enhancement

#335 pinning typing_extensions
  pyproject.toml
Labels: bug

#355 new ValueWithUnit implementation
  src/aind_data_schema/utils/units.py
  tests/test_units.py
Labels: enhancement
